project_name: zexample
before:
  hooks:
    - go mod tidy

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

builds:
  - binary: zexample
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

dockers:
- image_templates: ["docker.io/brothersam/zexample.{{ .Runtime.Goarch }}:{{ .Version }}"]
  dockerfile: Dockerfile
  goarch: amd64
  build_flag_templates:
  - --label=guance.image.title={{ .ProjectName }}
  - --label=guance.image.description={{ .ProjectName }}
  - --label=guance.image.url=https://github.com/brothersam66/testgoreleaser
  - --label=guance.image.source=https://github.com/brothersam66/testgoreleaser
  - --label=guance.image.version={{ .Version }}
  - --label=guance.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=guance.image.revision={{ .FullCommit }}
  - --label=guance.image.licenses=MIT
  
- image_templates: ["docker.io/brothersam/zexample.{{ .Runtime.Goarch }}:{{ .Version }}"]
  dockerfile: Dockerfile
  goarch: arm64
  build_flag_templates:
  - --label=guance.image.title={{ .ProjectName }}
  - --label=guance.image.description={{ .ProjectName }}
  - --label=guance.image.url=https://github.com/brothersam66/testgoreleaser
  - --label=guance.image.source=https://github.com/brothersam66/testgoreleaser
  - --label=guance.image.version={{ .Version }}
  - --label=guance.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=guance.image.revision={{ .FullCommit }}
  - --label=guance.image.licenses=MIT
  # - --label=org.opencontainers.image.title={{ .ProjectName }}
  # - --label=org.opencontainers.image.description={{ .ProjectName }}
  # - --label=org.opencontainers.image.url=https://github.com/brothersam66/testgoreleaser
  # - --label=org.opencontainers.image.source=https://github.com/brothersam66/testgoreleaser
  # - --label=org.opencontainers.image.version={{ .Version }}
  # - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  # - --label=org.opencontainers.image.revision={{ .FullCommit }}
  # - --label=org.opencontainers.image.licenses=MIT
nfpms:
- maintainer: Carlos A Becker <root@carlosbecker.dev>
  description: Sample project.
  homepage: https://github.com/brothersam66/tasktimer
  license: MIT
  formats:
  - deb
  - rpm
  - apk     


env_files:
  github_token: ~/go/src/github.com/github_token