# site_name: My Docs
# theme: 
#   name: material
#   language: zh
#   highlightjs: true

site_name: PPL 文档

#custom_dir: overrides/
theme:
  palette:
    primary: white
  name: material
  favicon: favicon.ico
  logo: logo.png
  language: zh
  features:
    - navigation.instant
    - search.suggest
    - toc.follow
    - navigation.tabs
    - navigation.expand

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: True
  - meta
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: false
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true

copyright: '&copy; 2013-2022 上海驻云信息科技有限公司 沪公网安备 31011502010862号 | 沪ICP备 13034243号-30'

# extra:
#   generator: false

# plugins:
#   - awesome-pages
#   - section-index
#   - search:
#       separator: '[\s\u200b\-]'

# Developer configuration
dev_addr: "0.0.0.0:8000"
