site_name: PPL Language

theme:
  name: material

plugins:
  - search
  - i18n:
      languages:
        zh: "中文"
        en: "English"
      default_language: 'en'

      translate_nav:
        zh:
          tutorials   : "用户指南"
          how-tos     : "最佳实践"
          explaination: "设计文档"
          references  : "参考文档"   
        en:
          tutorials   : "tutorials"
          how-tos     : "how-tos"
          explaination: "explaination"
          references  : "references"

nav:
- Overview: index.en.md
- 概述: index.zh.md
- tutorials:
  - tutorials/index.en.md
  - tutorials/index.zh.md
- how-tos:
  - how-tos/index.en.md
  - how-tos/index.zh.md
- explaination:
  - explaination/index.en.md
  - explaination/index.zh.md
- references:
  - references/pipeline.en.md
  - references/pipeline.zh.md
  - references/grok.en.md
  - references/grok.zh.md

extra:
  # Default mkdocs-material alternate links for untranslated pages
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/#site-language-selector
  alternate:
    - name: English
      link: "index.en"
      lang: en

    - name: 中文
      link: index.zh/
      lang: zh



